# Generated by Django 3.0.2 on 2020-01-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(null=True),
        ),
    ]
