# Generated by Django 3.0.2 on 2020-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200119_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='class_pattern',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
